[build]
  command = "npm run build"
  publish="C:\React_project\Project-Online-Shopping-master/build"
  base = "C:\React_project\Project-Online-Shopping-master/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200